"""Turn content/posts.json into seed SQL for the D1 database.

One-time migration of the 37 posts imported from Squarespace. Writes
db/seed.sql, which is applied with `wrangler d1 execute`.
"""
import json, os, re, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
posts = json.load(open(os.path.join(ROOT, "content", "posts.json"), encoding="utf-8"))

def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(int(v))
    return "'" + str(v).replace("'", "''") + "'"

def term_slug(t):
    return re.sub(r"[^a-z0-9]+", "-", t.lower()).strip("-") or "untagged"

now = int(time.time() * 1000)
out = ["-- Generated by tools/seed_d1.py — do not edit by hand.", "BEGIN TRANSACTION;"]

terms = {}
for p in posts:
    for kind, key in (("category", "categories"), ("tag", "tags")):
        for t in p.get(key) or []:
            terms.setdefault((kind, term_slug(t)), t)

for (kind, slug), name in sorted(terms.items()):
    out.append(f"INSERT OR IGNORE INTO terms (kind, name, slug) VALUES ({q(kind)}, {q(name)}, {q(slug)});")

for p in posts:
    body = p.get("body_clean", "").replace("%ROOT%", "../")
    out.append(
        "INSERT OR REPLACE INTO posts "
        "(slug, title, excerpt, body_html, thumb, author, status, published_at, created_at, updated_at) VALUES ("
        f"{q(p['slug'])}, {q(p['title'])}, {q((p.get('excerpt') or '')[:400])}, {q(body)}, "
        f"{q(p.get('local_thumb'))}, {q(p.get('author') or 'Megan Mossuto')}, 'published', "
        f"{q(p.get('published_ms'))}, {q(now)}, {q(now)});"
    )
    for kind, key in (("category", "categories"), ("tag", "tags")):
        for t in p.get(key) or []:
            out.append(
                "INSERT OR IGNORE INTO post_terms (post_id, term_id) SELECT p.id, t.id FROM posts p, terms t "
                f"WHERE p.slug = {q(p['slug'])} AND t.kind = {q(kind)} AND t.slug = {q(term_slug(t))};"
            )

out.append("COMMIT;")
dest = os.path.join(ROOT, "db", "seed.sql")
open(dest, "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"{len(posts)} posts, {len(terms)} terms -> db/seed.sql ({os.path.getsize(dest):,} bytes)")
